# coding=utf-8
from datetime import datetime

ALBUMS = {
    'Magia': {
        'release_date': datetime(1991, 6, 24),
        'songs': ['Sueños',
                  'Esta noche voy contigo',
                  'Lejos de tu amor',
                  'Magia',
                  'Cuentas conmigo',
                  'Cazador de amor',
                  'Gafas oscuras',
                  'Necesito de ti',
                  'Lejos de tu amor']
    },
    'Peligro': {
        'release_date': datetime(1993, 3, 25),
        'songs': ['Eres',
                  'Último momento',
                  'Tú serás la historia de mi vida',
                  'Peligro',
                  'Quince años',
                  'Brujería',
                  'Eterno amor',
                  'Controlas mi destino',
                  'Este amor es lo más bello del mundo']
    },
    'Pies Descalzos': {
        'release_date': datetime(1995, 10, 6),
        'songs': ['Estoy aquí',
                  'Antología',
                  'Un poco de amor',
                  'Quiero',
                  'Te necesito',
                  'Vuelve',
                  'Te espero sentada',
                  'Pies descalzos, sueños blancos',
                  'Pienso en ti',
                  '¿Dónde estás, corazón?',
                  'Se quiere, se mata']
    },
    'Donde Están los Ladrones': {
        'release_date': datetime(1998, 9, 29),
        'songs': ['Ciega, sordomuda',
                  'Si te vas',
                  'Moscas en la casa',
                  'No creo',
                  'Inevitable',
                  'Octavo día',
                  'Que vuelvas',
                  'Tú',
                  '¿Dónde están los ladrones?',
                  'Sombra de ti',
                  'Ojos así']
    },
    'Laundry Service': {
        'release_date': datetime(2001, 11, 13),
        'songs': ['Objection (Tango)',
                  'Underneath your clothes',
                  'Whenever, wherever',
                  'Rules',
                  'The one',
                  'Ready for the good times',
                  'Fool',
                  'Te dejo Madrid',
                  'Poem to a horse',
                  'Que me quedes tú',
                  'Eyes like yours (Ojos así)',
                  'Suerte',
                  'Te aviso, te anuncio']
    },
    'Fijacion Oral, Vol. 1': {
        'release_date': datetime(2005, 6, 3),
        'songs': ['En tus pupilas',
                  'La pared',
                  'La tortura',
                  'Obtener un sí',
                  'Día especial',
                  'Escondite inglés',
                  'No',
                  'Las de la intuición',
                  'Día de enero',
                  'Lo imprescindible',
                  'La pared',
                  'La tortura']
    },
    'Oral Fixation, Vol. 2': {
        'release_date': datetime(2005, 11, 25),
        'songs': ['How do you do',
                  'Don\'t bother',
                  'Illegal',
                  'The day and the time',
                  'Animal city',
                  'Dreams for plans',
                  'Hey you',
                  'Your embrace',
                  'Costume makes the clown',
                  'Something',
                  'Timor']
    },
    'She Wolf': {
        'release_date': datetime(2009, 06, 24),
        'songs': ['She wolf',
                  'Did it again',
                  'Long time',
                  'Why wait',
                  'Good stuff',
                  'Men in this town',
                  'Gypsy',
                  'Spy',
                  'Mon amour',
                  'Lo hecho está hecho',
                  'Años luz',
                  'Loba']
    },
    'Sale el Sol': {
        'release_date': datetime(2010, 10, 19),
        'songs': ['Sale el sol',
                  'Loca',
                  'Antes de las seis',
                  'Gordita',
                  'Addicted to you',
                  'Lo que más',
                  'Mariposas',
                  'Rabiosa',
                  'Devoción',
                  'Islands',
                  'Tu boca',
                  'Waka waka']
    },
    'Shakira': {
        'release_date': datetime(2014, 3, 21),
        'songs': ['Dare',
                  'Can\'t remember to forget you',
                  'Empire',
                  'You don\'t care about me',
                  'Cut me deep',
                  'Spotlight',
                  'Broken record',
                  'Medicine',
                  '23',
                  'The one thing',
                  'Nunca me acuerdo de olvidarte',
                  'Loca por ti']
    },
    'El Dorado': {
        'release_date': datetime(2017, 5, 26),
        'songs': ['Me enamoré',
                  'Nada',
                  'Chantaje',
                  'When a woman',
                  'Amarillo',
                  'Perro fiel',
                  'Trap',
                  'Comme moi',
                  'Coconut tree',
                  'La bicicleta',
                  'Déjà vu',
                  'What we said',
                  'Toneladas']
    }
}
